/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => PlayerStatCounterPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian3 = require("obsidian");

// view.ts
var import_obsidian = require("obsidian");
var VIEW_TYPE_PLAYER_STAT = "player-stat-counter";
var PlayerStatView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.countersList = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_PLAYER_STAT;
  }
  getDisplayText() {
    return "Player Stat Counter";
  }
  onOpen() {
    return __async(this, null, function* () {
      const container = this.containerEl.children[1];
      container.empty();
      container.style.padding = "10px";
      const header = container.createDiv("player-stat-header");
      const title = header.createEl("h2", { text: "Player Counters" });
      title.style.margin = "0 0 10px 0";
      title.style.fontSize = "18px";
      const addButton = header.createEl("button", { text: "+ Add Counter" });
      addButton.style.padding = "8px 16px";
      addButton.style.backgroundColor = "#007acc";
      addButton.style.color = "white";
      addButton.style.border = "none";
      addButton.style.borderRadius = "4px";
      addButton.style.cursor = "pointer";
      addButton.style.fontSize = "14px";
      addButton.style.marginTop = "10px";
      addButton.style.width = "100%";
      addButton.addEventListener("click", () => {
        this.showAddCounterDialog();
      });
      this.countersList = container.createDiv("counters-list");
      this.countersList.style.marginTop = "20px";
      this.renderCounters();
    });
  }
  renderCounters() {
    if (!this.countersList) return;
    this.countersList.empty();
    if (this.plugin.counters.length === 0) {
      this.countersList.createEl("p", {
        text: "No counters yet. Click 'Add Counter' to create one.",
        cls: "placeholder-text"
      });
      this.countersList.style.color = "#888";
      return;
    }
    const colors = ["#E8F4F8", "#FFF4E6"];
    this.plugin.counters.forEach((counter, index) => {
      const bgColor = colors[index % colors.length];
      const counterItem = this.countersList.createDiv("counter-item");
      counterItem.style.marginBottom = "12px";
      counterItem.style.padding = "16px";
      counterItem.style.backgroundColor = bgColor;
      counterItem.style.borderRadius = "8px";
      counterItem.style.border = "none";
      counterItem.style.display = "flex";
      counterItem.style.justifyContent = "space-between";
      counterItem.style.alignItems = "center";
      counterItem.style.minHeight = "60px";
      counterItem.style.boxShadow = "0 2px 4px rgba(0,0,0,0.1)";
      const leftSection = counterItem.createDiv();
      leftSection.style.display = "flex";
      leftSection.style.flexDirection = "column";
      leftSection.style.justifyContent = "center";
      leftSection.style.flex = "1";
      const nameDiv = leftSection.createDiv();
      nameDiv.style.color = "#000";
      nameDiv.style.fontWeight = "bold";
      nameDiv.style.fontSize = "16px";
      nameDiv.style.marginBottom = "4px";
      nameDiv.textContent = counter.key.charAt(0).toUpperCase() + counter.key.slice(1).replace(/-/g, " ");
      const valueDiv = leftSection.createDiv();
      valueDiv.style.color = "#000";
      valueDiv.style.fontSize = "28px";
      valueDiv.style.fontWeight = "bold";
      valueDiv.textContent = String(counter.value);
      const rightSection = counterItem.createDiv();
      rightSection.style.display = "flex";
      rightSection.style.gap = "6px";
      rightSection.style.marginLeft = "12px";
      const decrementBtn = rightSection.createEl("button", { text: "\u2212" });
      this.styleSmallButton(decrementBtn, "#dc3545");
      decrementBtn.addEventListener("click", () => __async(this, null, function* () {
        counter.value = Math.max(this.plugin.settings.minValue, counter.value - 1);
        counter.history.push({
          timestamp: (/* @__PURE__ */ new Date()).toISOString(),
          value: counter.value
        });
        yield this.plugin.saveCounters();
        this.renderCounters();
      }));
      const incrementBtn = rightSection.createEl("button", { text: "+" });
      this.styleSmallButton(incrementBtn, "#28a745");
      incrementBtn.addEventListener("click", () => __async(this, null, function* () {
        const maxVal = this.plugin.settings.maxValue || Infinity;
        counter.value = Math.min(maxVal, counter.value + 1);
        counter.history.push({
          timestamp: (/* @__PURE__ */ new Date()).toISOString(),
          value: counter.value
        });
        yield this.plugin.saveCounters();
        this.renderCounters();
      }));
      const deleteBtn = rightSection.createEl("button", { text: "\u2715" });
      this.styleSmallButton(deleteBtn, "#999");
      deleteBtn.addEventListener("click", () => __async(this, null, function* () {
        if (this.plugin.settings.showDeleteConfirm) {
          if (!confirm(`Delete counter "${counter.key}"?`)) return;
        }
        this.plugin.counters.splice(index, 1);
        yield this.plugin.saveCounters();
        this.renderCounters();
      }));
      const editBtn = rightSection.createEl("button", { text: "\u270E" });
      this.styleSmallButton(editBtn, "#0066cc");
      editBtn.addEventListener("click", () => __async(this, null, function* () {
        this.showEditCounterDialog(counter);
      }));
    });
  }
  styleSmallButton(btn, bgColor) {
    btn.style.padding = "6px 12px";
    btn.style.backgroundColor = bgColor;
    btn.style.color = "white";
    btn.style.border = "none";
    btn.style.borderRadius = "4px";
    btn.style.cursor = "pointer";
    btn.style.fontSize = "14px";
    btn.style.fontWeight = "bold";
    btn.style.whiteSpace = "nowrap";
    btn.style.minWidth = "32px";
  }
  showAddCounterDialog() {
    const modal = document.createElement("div");
    modal.style.position = "fixed";
    modal.style.top = "50%";
    modal.style.left = "50%";
    modal.style.transform = "translate(-50%, -50%)";
    modal.style.backgroundColor = "var(--background-primary)";
    modal.style.border = "1px solid var(--divider-color)";
    modal.style.borderRadius = "8px";
    modal.style.padding = "20px";
    modal.style.boxShadow = "0 4px 12px rgba(0, 0, 0, 0.3)";
    modal.style.zIndex = "1000";
    modal.style.minWidth = "300px";
    modal.style.maxHeight = "80vh";
    modal.style.overflowY = "auto";
    const title = modal.createEl("h3", { text: "Add New Counter" });
    title.style.marginTop = "0";
    const form = modal.createDiv("form");
    const nameLabel = form.createEl("label", { text: "Counter Name:" });
    nameLabel.style.display = "block";
    nameLabel.style.marginBottom = "5px";
    nameLabel.style.fontWeight = "bold";
    const nameInput = form.createEl("input", {
      type: "text",
      placeholder: "e.g., Health, Mana, Experience"
    });
    nameInput.style.width = "100%";
    nameInput.style.padding = "8px";
    nameInput.style.marginBottom = "15px";
    nameInput.style.border = "1px solid var(--divider-color)";
    nameInput.style.borderRadius = "4px";
    nameInput.style.boxSizing = "border-box";
    const logLabel = form.createEl("label", { text: "Log/Notes:" });
    logLabel.style.display = "block";
    logLabel.style.marginBottom = "5px";
    logLabel.style.fontWeight = "bold";
    const logInput = form.createEl("textarea");
    logInput.placeholder = "Add notes or log information about this counter";
    logInput.style.width = "100%";
    logInput.style.padding = "8px";
    logInput.style.marginBottom = "15px";
    logInput.style.border = "1px solid var(--divider-color)";
    logInput.style.borderRadius = "4px";
    logInput.style.boxSizing = "border-box";
    logInput.style.minHeight = "100px";
    logInput.style.fontFamily = "monospace";
    logInput.style.fontSize = "12px";
    const buttonContainer = form.createDiv();
    buttonContainer.style.display = "flex";
    buttonContainer.style.gap = "10px";
    buttonContainer.style.justifyContent = "flex-end";
    const createBtn = buttonContainer.createEl("button", { text: "Create" });
    createBtn.style.padding = "8px 16px";
    createBtn.style.backgroundColor = "#28a745";
    createBtn.style.color = "white";
    createBtn.style.border = "none";
    createBtn.style.borderRadius = "4px";
    createBtn.style.cursor = "pointer";
    const cancelBtn = buttonContainer.createEl("button", { text: "Cancel" });
    cancelBtn.style.padding = "8px 16px";
    cancelBtn.style.backgroundColor = "#6c757d";
    cancelBtn.style.color = "white";
    cancelBtn.style.border = "none";
    cancelBtn.style.borderRadius = "4px";
    cancelBtn.style.cursor = "pointer";
    const overlay = document.createElement("div");
    overlay.style.position = "fixed";
    overlay.style.top = "0";
    overlay.style.left = "0";
    overlay.style.width = "100%";
    overlay.style.height = "100%";
    overlay.style.backgroundColor = "rgba(0, 0, 0, 0.5)";
    overlay.style.zIndex = "999";
    createBtn.addEventListener("click", () => __async(this, null, function* () {
      const counterName = nameInput.value.trim();
      if (counterName) {
        const newCounter = {
          key: counterName.toLowerCase().replace(/\s+/g, "-"),
          type: "simple",
          value: 0,
          log: logInput.value.trim(),
          history: [{ timestamp: (/* @__PURE__ */ new Date()).toISOString(), value: 0 }]
        };
        this.plugin.counters.push(newCounter);
        console.log("Counter created:", newCounter);
        yield this.plugin.saveCounters();
        overlay.remove();
        modal.remove();
        this.renderCounters();
      }
    }));
    cancelBtn.addEventListener("click", () => {
      overlay.remove();
      modal.remove();
    });
    overlay.addEventListener("click", (e) => {
      if (e.target === overlay) {
        overlay.remove();
        modal.remove();
      }
    });
    document.body.appendChild(overlay);
    document.body.appendChild(modal);
    nameInput.focus();
  }
  showEditCounterDialog(counter) {
    const modal = document.createElement("div");
    modal.style.position = "fixed";
    modal.style.top = "50%";
    modal.style.left = "50%";
    modal.style.transform = "translate(-50%, -50%)";
    modal.style.backgroundColor = "var(--background-primary)";
    modal.style.border = "1px solid var(--divider-color)";
    modal.style.borderRadius = "8px";
    modal.style.padding = "20px";
    modal.style.boxShadow = "0 4px 12px rgba(0, 0, 0, 0.3)";
    modal.style.zIndex = "1000";
    modal.style.minWidth = "300px";
    modal.style.maxHeight = "80vh";
    modal.style.overflowY = "auto";
    const title = modal.createEl("h3", { text: "Edit Counter" });
    title.style.marginTop = "0";
    const form = modal.createDiv("form");
    const nameLabel = form.createEl("label", { text: "Counter Name:" });
    nameLabel.style.display = "block";
    nameLabel.style.marginBottom = "5px";
    nameLabel.style.fontWeight = "bold";
    const nameInput = form.createEl("input", {
      type: "text",
      placeholder: "e.g., Health, Mana, Experience"
    });
    nameInput.value = counter.key.charAt(0).toUpperCase() + counter.key.slice(1).replace(/-/g, " ");
    nameInput.style.width = "100%";
    nameInput.style.padding = "8px";
    nameInput.style.marginBottom = "15px";
    nameInput.style.border = "1px solid var(--divider-color)";
    nameInput.style.borderRadius = "4px";
    nameInput.style.boxSizing = "border-box";
    const logLabel = form.createEl("label", { text: "Log/Notes:" });
    logLabel.style.display = "block";
    logLabel.style.marginBottom = "5px";
    logLabel.style.fontWeight = "bold";
    const logInput = form.createEl("textarea");
    logInput.placeholder = "Add notes or log information about this counter";
    logInput.value = counter.log || "";
    logInput.style.width = "100%";
    logInput.style.padding = "8px";
    logInput.style.marginBottom = "15px";
    logInput.style.border = "1px solid var(--divider-color)";
    logInput.style.borderRadius = "4px";
    logInput.style.boxSizing = "border-box";
    logInput.style.minHeight = "100px";
    logInput.style.fontFamily = "monospace";
    logInput.style.fontSize = "12px";
    const buttonContainer = form.createDiv();
    buttonContainer.style.display = "flex";
    buttonContainer.style.gap = "10px";
    buttonContainer.style.justifyContent = "flex-end";
    const saveBtn = buttonContainer.createEl("button", { text: "Save" });
    saveBtn.style.padding = "8px 16px";
    saveBtn.style.backgroundColor = "#007bff";
    saveBtn.style.color = "white";
    saveBtn.style.border = "none";
    saveBtn.style.borderRadius = "4px";
    saveBtn.style.cursor = "pointer";
    const cancelBtn = buttonContainer.createEl("button", { text: "Cancel" });
    cancelBtn.style.padding = "8px 16px";
    cancelBtn.style.backgroundColor = "#6c757d";
    cancelBtn.style.color = "white";
    cancelBtn.style.border = "none";
    cancelBtn.style.borderRadius = "4px";
    cancelBtn.style.cursor = "pointer";
    const overlay = document.createElement("div");
    overlay.style.position = "fixed";
    overlay.style.top = "0";
    overlay.style.left = "0";
    overlay.style.width = "100%";
    overlay.style.height = "100%";
    overlay.style.backgroundColor = "rgba(0, 0, 0, 0.5)";
    overlay.style.zIndex = "999";
    saveBtn.addEventListener("click", () => __async(this, null, function* () {
      const newName = nameInput.value.trim();
      if (newName) {
        counter.key = newName.toLowerCase().replace(/\s+/g, "-");
        counter.log = logInput.value.trim();
        yield this.plugin.saveCounters();
        overlay.remove();
        modal.remove();
        this.renderCounters();
      }
    }));
    cancelBtn.addEventListener("click", () => {
      overlay.remove();
      modal.remove();
    });
    overlay.addEventListener("click", (e) => {
      if (e.target === overlay) {
        overlay.remove();
        modal.remove();
      }
    });
    document.body.appendChild(overlay);
    document.body.appendChild(modal);
    nameInput.focus();
  }
  onClose() {
    return __async(this, null, function* () {
    });
  }
};

// settings.ts
var import_obsidian2 = require("obsidian");
var PlayerStatSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Player Stat Counter Settings" });
    new import_obsidian2.Setting(containerEl).setName("Counter display format").setDesc("Choose how counters are displayed").addDropdown(
      (dropdown) => dropdown.addOption("compact", "Compact (value only)").addOption("full", "Full (name + value)").setValue(this.plugin.settings.displayFormat).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.displayFormat = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian2.Setting(containerEl).setName("Enable counter history").setDesc("Keep track of all counter changes with timestamps").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.trackHistory).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.trackHistory = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian2.Setting(containerEl).setName("Show delete confirmation").setDesc("Ask for confirmation before deleting a counter").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showDeleteConfirm).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.showDeleteConfirm = value;
        yield this.plugin.saveSettings();
      }))
    );
    new import_obsidian2.Setting(containerEl).setName("Minimum counter value").setDesc("Set the minimum value counters can reach").addText(
      (text) => text.setPlaceholder("0").setValue(String(this.plugin.settings.minValue)).onChange((value) => __async(this, null, function* () {
        const num = parseInt(value);
        if (!isNaN(num)) {
          this.plugin.settings.minValue = num;
          yield this.plugin.saveSettings();
        }
      }))
    );
    new import_obsidian2.Setting(containerEl).setName("Maximum counter value").setDesc("Set the maximum value counters can reach (leave empty for unlimited)").addText(
      (text) => text.setPlaceholder("unlimited").setValue(this.plugin.settings.maxValue ? String(this.plugin.settings.maxValue) : "").onChange((value) => __async(this, null, function* () {
        const num = value === "" ? 0 : parseInt(value);
        if (value === "" || !isNaN(num)) {
          this.plugin.settings.maxValue = num;
          yield this.plugin.saveSettings();
        }
      }))
    );
    new import_obsidian2.Setting(containerEl).setName("Button style").setDesc("Choose button appearance").addDropdown(
      (dropdown) => dropdown.addOption("default", "Default").addOption("large", "Large").addOption("minimal", "Minimal").setValue(this.plugin.settings.buttonStyle).onChange((value) => __async(this, null, function* () {
        this.plugin.settings.buttonStyle = value;
        yield this.plugin.saveSettings();
      }))
    );
    containerEl.createEl("hr");
    containerEl.createEl("h3", { text: "Data Management" });
    new import_obsidian2.Setting(containerEl).setName("Export counters").setDesc("Download your counter data as JSON").addButton(
      (button) => button.setButtonText("Export").onClick(() => {
        const dataStr = JSON.stringify(this.plugin.counters, null, 2);
        const dataBlob = new Blob([dataStr], { type: "application/json" });
        const url = URL.createObjectURL(dataBlob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `player-counters-${(/* @__PURE__ */ new Date()).toISOString().split("T")[0]}.json`;
        link.click();
        URL.revokeObjectURL(url);
      })
    );
    new import_obsidian2.Setting(containerEl).setName("Clear all counters").setDesc("WARNING: This will delete all counters permanently").addButton(
      (button) => button.setButtonText("Clear All").setWarning().onClick(() => __async(this, null, function* () {
        if (confirm("Are you sure you want to delete all counters? This cannot be undone.")) {
          this.plugin.counters = [];
          yield this.plugin.saveCounters();
          this.display();
        }
      }))
    );
  }
};

// main.ts
var DEFAULT_SETTINGS = {
  displayFormat: "full",
  trackHistory: true,
  showDeleteConfirm: true,
  minValue: 0,
  maxValue: 0,
  buttonStyle: "default"
};
var PlayerStatCounterPlugin = class extends import_obsidian3.Plugin {
  constructor() {
    super(...arguments);
    this.view = null;
    this.counters = [];
    this.settings = DEFAULT_SETTINGS;
  }
  onload() {
    return __async(this, null, function* () {
      const savedSettings = yield this.loadData();
      if (savedSettings && savedSettings.settings) {
        this.settings = __spreadValues(__spreadValues({}, DEFAULT_SETTINGS), savedSettings.settings);
      }
      if (savedSettings && savedSettings.counters) {
        this.counters = savedSettings.counters;
      }
      this.addSettingTab(new PlayerStatSettingTab(this.app, this));
      this.registerView(
        VIEW_TYPE_PLAYER_STAT,
        (leaf) => {
          this.view = new PlayerStatView(leaf, this);
          return this.view;
        }
      );
      this.addRibbonIcon("dice", "Player Stat Counter", () => {
        this.activateView();
      });
      this.addCommand({
        id: "open-player-stat-counter",
        name: "Open Player Stat Counter",
        callback: () => this.activateView()
      });
    });
  }
  activateView() {
    return __async(this, null, function* () {
      this.app.workspace.getRightLeaf(false).setViewState({
        type: VIEW_TYPE_PLAYER_STAT,
        active: true
      });
    });
  }
  saveCounters() {
    return __async(this, null, function* () {
      yield this.saveData({ counters: this.counters, settings: this.settings });
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData({ counters: this.counters, settings: this.settings });
    });
  }
};
